### ISSUE TITLE
failed to compile ( Argument of type '{ query: string; sortBy: string; }' )

### ISSUE THREAD

**Issue by alisufiyan123** [BuilderIO/nextjs-shopify#36] opened 2022-07-14 08:36 UTC
problem poping when trying to npm run build and also in build checking while deploying on vercel ???

Type error: Argument of type '{ query: string; sortBy: string; }' is not assignable to parameter of type 'Query'.
  Object literal may only specify known properties, and 'sortBy' does not exist in type 'Query'.

./lib/shopify/storefront-data-hooks/src/api/operations.ts:70:5
  68 |   return client.product.fetchQuery({
  69 |     query: searchString ? `title:*${searchString}*` : '',
> 70 |     sortBy: `title`,
     |     ^
  71 |   })
  72 | }

**Comment by alisufiyan123** [comment] 2022-07-30 11:39
anyone ???

**Comment by gustavocodess** [comment] 2022-08-03 02:47
Hey @alisufiyan123, we found the cause of the issue, We'll fix and let you know right away.

**Comment by teleaziz** [comment] 2022-08-15 17:07
This is fixed and merged in #37

**Closed by teleaziz** 2022-08-15 17:07 UTC
